import { ResumeStructure } from "../structure";
import {
  b_amz01,
  b_amz02,
  b_amz03,
  b_amz04,
  b_amz05,
  b_amz06,
  b_amz07,
  b_amz08,
  b_amz09,
  b_amz10,
  b_atom1,
  b_atom2,
  b_chat1,
  b_eecs1,
  b_fflc1,
  b_fflc2,
  b_fflc3,
  b_fflc4,
  b_flwd1,
  b_flwd2,
  b_ieee1,
  b_lbl01,
  b_lbl02,
  b_lbl03,
  b_msg01,
  b_msg02,
  b_msg03,
  b_nim01,
  b_nim02,
  b_nim03,
  b_nim04,
  b_nim05,
  b_nim06,
  b_nim07,
  b_pent1,
  b_pent2,
  b_pent3,
  b_pent4,
} from "./tailors/general-tailor";
import { SKILL_OBJECT, LANG_OBJECT } from "./master-input2";

export const raw: ResumeStructure = {
  core: {
    contact: {
      type: "Contact",
      name: "Joey Zhu",
      number: "+1 (925) 858-2048",
      email: "joey.j.zhu@gmail.com",
    },
    location: {
      type: "Location",
      city: "San Ramon",
      state: "CA",
      zipCode: "94583",
    },
    title: "Software Engineer",
    homesiteUrl: "https://joeyjzhu.com",
  },
  skills: {
    skillMap: new Map(),
    skillObj: SKILL_OBJECT,
    langObj: LANG_OBJECT,
  },
  degrees: [{
    schoolName: "University of California, Berkeley",
    degree: "B.A.",
    major: "Computer Science",
    location: {
      type: "Location",
      address: "110 Sproul Hall",
      city: "Berkeley",
      state: "CA",
      zipCode: "94720",
    },
    startDate: { type: "Date", month: 8, day: 29, year: 2019 },
    endDate: { type: "Date", month: 12, day: 31, year: 2022 },
    courses: [
      {
        type: "Course",
        className: "Probability Theory",
        isMajor: true,
        codeName: "COMPSCI 126",
      },
      {
        type: "Course",
        className: "Neural Networks",
        isMajor: true,
        codeName: "COMPSCI 182",
      },
      {
        type: "Course",
        className: "Cybersecurity",
        isMajor: true,
        codeName: "COMPSCI 161",
      },
      {
        type: "Course",
        className: "Algorithm Theory",
        isMajor: true,
        codeName: "COMPSCI 170",
      },
      {
        type: "Course",
        className: "Intro to Machine Learning",
        isMajor: true,
        codeName: "COMPSCI 189",
      },
      {
        type: "Course",
        className: "Differential Equations",
        isMajor: false,
        codeName: "PHYSICS 89",
      },
      {
        type: "Course",
        className: "Analytic Mechanics",
        isMajor: false,
        codeName: "PHYSICS 105",
      },
      {
        type: "Course",
        className: "Electrodynamics",
        isMajor: false,
        codeName: "PHYSICS 110A",
      },
      {
        type: "Course",
        className: "Quantum Mechanics",
        isMajor: false,
        codeName: "PHYSICS 137A",
      },
      {
        type: "Course",
        className: "Statistical Mechanics",
        isMajor: false,
        codeName: "PHYSICS 112",
      },
    ],
    gpa: 3.5,
  },
  {
    schoolName: "Coursera",
    location: {
      type: "Location",
      address: "",
      city: "Online",
      state: "",
      zipCode: "",
    },
    startDate: { type: "Date", month: 6, day: 1, year: 2023 },
    courses: [
      {
        type: "Course",
        className: "React.js",
        isMajor: true,
        codeName: "Meta iOS Developer",
      },
      {
        type: "Course",
        className: "React Native",
        isMajor: true,
        codeName: "Meta iOS Developer",
      },
      {
        type: "Course",
        className: "VR, XR Development",
        isMajor: true,
        codeName: "U Michigan",
      },
      {
        type: "Course",
        className: "Developing with Unity",
        isMajor: true,
        codeName: "U Michigan",
      },
    ],
  },],
  blurb: { body: b_msg01 + b_msg02 + b_msg03 },
  experienceEntries: [
    {
      companyName: "UC Berkeley EECS",
      team: "Data Structures Course Summer 2020",
      role: "Academic Intern",
      isInternship: true,
      isVolunteer: true,
      location: {
        type: "Location",
        address: "Cory Hall",
        city: "Berkeley",
        state: "CA",
        zipCode: "94720",
      },
      startDate: { type: "Date", month: 6, day: 15, year: 2020 },
      endDate: { type: "Date", month: 8, day: 15, year: 2020 },
      supervisor: {
        type: "Contact",
        name: "Eric Tang",
        email: "erictang000@berkeley.edu",
      },
      bulletPoints: [{ type: "BulletPoint", body: b_eecs1 }],
    },
    {
      companyName: "IEEE",
      team: "Berkeley Chapter",
      role: "Marketing Team Officer",
      isInternship: false,
      isVolunteer: true,
      location: {
        type: "Location",
        address: "Cory Hall",
        city: "Berkeley",
        state: "CA",
        zipCode: "94720",
      },
      startDate: { type: "Date", month: 1, day: 18, year: 2022 },
      endDate: { type: "Date", month: 5, day: 6, year: 2022 },
      supervisor: {
        type: "Contact",
        name: "Katja Maucec",
        email: "katja.maucec@berkeley.edu",
      },
      bulletPoints: [{ type: "BulletPoint", body: b_ieee1 }],
    },
    {
      companyName: "Amazon",
      team: "Online Agreement Services",
      role: "Software Developer & Engineer Intern",
      isInternship: true,
      isVolunteer: false,
      location: {
        type: "Location",
        address: "410 Terry Ave.",
        city: "Seattle",
        state: "WA",
        zipCode: "98109",
      },
      startDate: { type: "Date", month: 1, day: 18, year: 2022 },
      endDate: { type: "Date", month: 5, day: 6, year: 2022 },
      supervisor: {
        type: "Contact",
        name: "Akshay Mittal",
        number: "+1 (425) 279-3270",
        email: "akshaym@amazon.com",
      },
      bulletPoints: [
        { type: "BulletPoint", body: b_amz01 },
        { type: "BulletPoint", body: b_amz02 },
        { type: "BulletPoint", body: b_amz03 },
        { type: "BulletPoint", body: b_amz04 },
        { type: "BulletPoint", body: b_amz05 },
        { type: "BulletPoint", body: b_amz06 },
        { type: "BulletPoint", body: b_amz07 },
        { type: "BulletPoint", body: b_amz08 },
        { type: "BulletPoint", body: b_amz09 },
        { type: "BulletPoint", body: b_amz10 },
      ],
    },
    {
      companyName: "NimbleRx",
      team: "Platform Team",
      role: "Software Engineer Intern",
      isInternship: true,
      isVolunteer: false,
      location: {
        type: "Location",
        address: "2317 Broadway",
        city: "Redwood City",
        state: "CA",
        zipCode: "94063",
      },
      startDate: { type: "Date", month: 5, day: 14, year: 2022 },
      endDate: { type: "Date", month: 8, day: 10, year: 2022 },
      supervisor: {
        type: "Contact",
        name: "Vladislav Yavichev",
        email: "https://www.linkedin.com/in/yavichev/",
      },
      bulletPoints: [
        { type: "BulletPoint", body: b_nim01 },
        { type: "BulletPoint", body: b_nim02 },
        { type: "BulletPoint", body: b_nim03 },
        { type: "BulletPoint", body: b_nim04 },
        { type: "BulletPoint", body: b_nim05 },
        { type: "BulletPoint", body: b_nim06 },
        { type: "BulletPoint", body: b_nim07 },
      ],
    },
    {
      companyName: "Lawrence Berkeley National Laboratory",
      team: "ATAP Division",
      role: "Software Engineer Intern",
      isInternship: true,
      isVolunteer: false,
      location: {
        type: "Location",
        address: "1 Cyclotron Road",
        city: "Berkeley",
        state: "CA",
        zipCode: "94720",
      },
      startDate: { type: "Date", month: 8, day: 17, year: 2022 },
      endDate: { type: "Date", month: 11, day: 1, year: 2022 },
      supervisor: {
        type: "Contact",
        name: "Axel Huebl",
        email: "axelhuebl@lbl.gov",
      },
      bulletPoints: [
        { type: "BulletPoint", body: b_lbl01 },
        { type: "BulletPoint", body: b_lbl02 },
        { type: "BulletPoint", body: b_lbl03 },
      ],
    },
    {
      companyName: "",
      team: "",
      role: "Freelance Web Developer",
      isInternship: false,
      isVolunteer: true,
      location: {
        type: "Location",
        city: "San Ramon",
        state: "CA",
        zipCode: "94583",
      },
      startDate: { type: "Date", month: 1, day: 1, year: 2023 },
      endDate: { type: "Date", month: 7, day: 1, year: 2023 },
      supervisor: {
        type: "Contact",
        name: "Joey Zhu",
        email: "joey.j.zhu@gmail.com",
      },
      bulletPoints: [
        { type: "BulletPoint", body: b_flwd1 },
        { type: "BulletPoint", body: b_flwd2 },
      ],
    },
    {
      companyName: "FOOD For Lane County",
      team: "Engineering",
      role: "Tech Lead",
      isInternship: false,
      isVolunteer: true,
      location: {
        type: "Location",
        address: "770 Bailey Hill Rd",
        city: "Eugene",
        state: "OR",
        zipCode: "97402",
      },
      startDate: { type: "Date", month: 7, day: 1, year: 2023 },
      supervisor: {
        type: "Contact",
        name: "Yizhao Yang",
        email: "yizhao@uoregon.edu",
      },
      bulletPoints: [
        { type: "BulletPoint", body: b_fflc1 },
        { type: "BulletPoint", body: b_fflc2 },
        { type: "BulletPoint", body: b_fflc3 },
        { type: "BulletPoint", isHidden: true, body: b_fflc4 },
      ],
    },
  ],
  projectEntries: [
    {
      name: "Atom Visualizer",
      isHidden: true,
      projectLink: "https://github.com/np-eazy/electron-cloud",
      role: "Solo Developer",
      location: {
        type: "Location",
        city: "San Ramon",
        state: "CA",
        zipCode: "94583",
      },
      startDate: { type: "Date", month: 2, day: 1, year: 2023 },
      endDate: { type: "Date", month: 3, day: 1, year: 2023 },
      bulletPoints: [
        { type: "BulletPoint", body: b_atom1 },
        { type: "BulletPoint", body: b_atom2 },
      ],
    },
    {
      name: "Pentaquad",
      projectLink: "https://github.com/np-eazy/Pentaquad",
      role: "Solo Developer",
      location: {
        type: "Location",
        city: "San Ramon",
        state: "CA",
        zipCode: "94583",
      },
      startDate: { type: "Date", month: 3, day: 1, year: 2023 },
      endDate: { type: "Date", month: 8, day: 1, year: 2023 },
      bulletPoints: [
        { type: "BulletPoint", body: b_pent1 },
        { type: "BulletPoint", body: b_pent2 },
        { type: "BulletPoint", body: b_pent3 },
        { type: "BulletPoint", body: b_pent4 },
      ],
    },
    {
      name: "ChatBoba",
      isHidden: true,
      projectLink: "https://chatboba.com/",
      role: "Developer",
      location: {
        type: "Location",
        city: "San Ramon",
        state: "CA",
        zipCode: "94583",
      },
      startDate: { type: "Date", month: 5, day: 1, year: 2023 },
      endDate: { type: "Date", month: 6, day: 1, year: 2023 },
      bulletPoints: [{ type: "BulletPoint", body: b_chat1 }],
    },
  ],
  hobbies: [
    { name: "Piano", description: "I've played piano since I was 5" },
    { name: "Cello", description: "I've played cello since I was 8" },
    {
      name: "Oil Painting",
      description: "I've done oil painting since I was 12",
    },
  ],
};
