export const LANG_OBJECT = {
    "Python": 3,
    "JavaScript": 3,
    "HTML": 2,
    "CSS": 2,
    "Typescript": 1,
    "React_dot_js": 2,
    "Java": 2,
    "Spring_Boot": 1,
    "C": 1,
    "Numpy": 1,
    "Three_dot_js": 0,
    "C_plus_plus": 0,
    "Scipy": 0,
    "PyTorch": 0,
};

export const SKILL_OBJECT = {
    "VSCode": 3,
    "Git": 3,
    "Photoshop": 2,
    "Illustrator": 2,
    "AWS_CDK": 1,
    "AWS_Lambda": 1,
    "AWS_ECS": 1,
    "AWS_Dynamo_DB": 1,
    "AWS_S3": 1,
    "AWS_API_Gateway": 1,
    "AWS_SQS": 1,
    "AWS_SNS": 1,
    "AWS_Cloudwatch": 1,
    "Kibana": 0,
    "Jira": 0,
    "Confluence": 0,
    "Jenkins": 0,
    "Gradle": 0,
    "Mockito": 0,
    "Tailwind_CSS": 0,
    "ElasticSearch": 0,
    "Docker": 0,
};