import { ResumeStructure } from './structure';

export const raw: ResumeStructure = {
    core: {
        contact: {type: "Contact",
            name: "Joey Zhu",
            number: "+1 (425) 279-3270",
            email: "akshaym@amazon.com",
        },
        location: {type: "Location",
            city: "San Ramon",
            state: "CA",
            zipCode: "94583",
        },
        homesiteUrl: "https://joeyjzhu.com",
    },
    skills: {
        skillMap: new Map(),
    },
    degree: {
        schoolName: "University of California, Berkeley",
        degree: "B.A.",
        major: "Computer Science",
        location: {type: "Location",
                address: "2021 7th Street",
                city: "Seattle",
                state: "WA",
                zipCode: "94583",
            },
        startDate: {type: "Date",
            month: 8, day: 29, year: 2019, 
        },
        endDate: {type: "Date",
            month: 12, day: 31, year: 2022, 
        },
        courses: [
            {type: "Course",
                className: "Intro to Machine Learning",
                isMajor: true,
                codeName: "CS 189",
                description: "Probabilistic and geometric ML methods, MLEs, NNs, SVMs, Regularization"
            },
        ],
        gpa: 3.5,
    },
    experienceEntries: [
        {
            name: "Amazon",
            team: "Online Agreement Services",
            role: "Software Development Engineer",
            isInternship: true,
            isVolunteer: false,
            location: {type: "Location",
                address: "2021 7th Street",
                city: "Seattle",
                state: "WA",
                zipCode: "98121",
            },
            startDate: {type: "Date",
                month: 1, day: 6, year: 2022, 
            },
            endDate: {type: "Date",
                month: 1, day: 6, year: 2022,
            },
            supervisor: {type: "Contact",
                name: "Akshay Mittal",
                number: "+1 (425) 279-3270",
                email: "akshaym@amazon.com",
            },
            bulletPoints: [
                {type: "BulletPoint",
                    body: "",
                    impact: "",
                },
            ]
        },
    ],
    projectEntries: [
        {
            name: "Pentaquad",
            projectLink: "https://github.com/np-eazy/Pentaquad",
            role: "Solo Developer",
            location: {type: "Location",
                city: "San Ramon",
                state: "WA",
                zipCode: "94583",
            },
            startDate: {type: "Date",
                month: 1, day: 6, year: 2022, 
            },
            endDate: {type: "Date",
                month: 1, day: 6, year: 2022,
            },
            supervisor: {type: "Contact",
                name: "Akshay Mittal",
                number: "+1 (425) 279-3270",
                email: "akshaym@amazon.com",
            },
            bulletPoints: [
                {type: "BulletPoint",
                    body: "",
                    impact: "",
                },
            ]
        },
    ],
  }

raw.skills.skillMap.set("Python", 3);